[project]
name = "robo-pilot-backend"
version = "0.1.0"
description = "robo pilot backend service."
authors = [{ name = "Sachin Kumar", email = "sachinkumar.ar97@gmail.com" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
]